name: Auto Update noVNC and websockify

on:
  schedule:
    - cron: '50 15 * * 4'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current versions from Dockerfile
        id: current
        run: |
          novnc_current=$(grep "ARG NOVNC_VERSION=" Dockerfile | cut -d'=' -f2)
          websockify_current=$(grep "ARG WEBSOCKIFY_VERSION=" Dockerfile | cut -d'=' -f2)
          echo "novnc=$novnc_current" >> $GITHUB_OUTPUT
          echo "websockify=$websockify_current" >> $GITHUB_OUTPUT
          echo "Current noVNC version: $novnc_current"
          echo "Current websockify version: $websockify_current"

      - name: Get latest versions using GraphQL
        id: latest
        run: |
          response=$(gh api graphql -f query='
            query {
              novnc: repository(owner: "novnc", name: "noVNC") {
                latestRelease {
                  tagName
                }
              }
              websockify: repository(owner: "novnc", name: "websockify") {
                latestRelease {
                  tagName
                }
              }
            }
          ')

          novnc_version=$(echo "$response" | jq -r '.data.novnc.latestRelease.tagName')
          websockify_version=$(echo "$response" | jq -r '.data.websockify.latestRelease.tagName')

          echo "novnc=$novnc_version" >> $GITHUB_OUTPUT
          echo "websockify=$websockify_version" >> $GITHUB_OUTPUT
          echo "Latest noVNC version: $novnc_version"
          echo "Latest websockify version: $websockify_version"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if update is needed
        id: update_needed
        run: |
          update_needed=false

          if [ "${{ steps.current.outputs.novnc }}" != "${{ steps.latest.outputs.novnc }}" ]; then
            echo "noVNC update needed: ${{ steps.current.outputs.novnc }} -> ${{ steps.latest.outputs.novnc }}"
            update_needed=true
          fi

          if [ "${{ steps.current.outputs.websockify }}" != "${{ steps.latest.outputs.websockify }}" ]; then
            echo "websockify update needed: ${{ steps.current.outputs.websockify }} -> ${{ steps.latest.outputs.websockify }}"
            update_needed=true
          fi

          echo "update_needed=$update_needed" >> $GITHUB_OUTPUT

      - name: Update Dockerfile
        if: steps.update_needed.outputs.update_needed == 'true'
        run: |
          sed -i "s/ARG NOVNC_VERSION=.*/ARG NOVNC_VERSION=${{ steps.latest.outputs.novnc }}/" Dockerfile
          sed -i "s/ARG WEBSOCKIFY_VERSION=.*/ARG WEBSOCKIFY_VERSION=${{ steps.latest.outputs.websockify }}/" Dockerfile

          echo "Updated Dockerfile with new versions"
          cat Dockerfile

      - name: Commit and push changes
        if: steps.update_needed.outputs.update_needed == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Dockerfile
          git commit -m "Auto-update: noVNC ${{ steps.latest.outputs.novnc }}, websockify ${{ steps.latest.outputs.websockify }}"
          git push

      - name: Setup Docker buildx
        if: steps.update_needed.outputs.update_needed == 'true'
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Login to registry ${{ env.REGISTRY }}
        if: steps.update_needed.outputs.update_needed == 'true'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        if: steps.update_needed.outputs.update_needed == 'true'
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=novnc-${{ steps.latest.outputs.novnc }}-websockify-${{ steps.latest.outputs.websockify }}

      - name: Build and push Docker image
        if: steps.update_needed.outputs.update_needed == 'true'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
